### ISSUE TITLE
Metrics

### ISSUE THREAD

**Issue by iandoug** [eamouee/oatpie#1]
Hi

How did you measure your performance?

Thanks, Ian

**Comment by eamouee** [comment]
Hi, Ian

Thanks to your consideration.

It has supposed that all keys, for the benchmark simulation, categorized in 8 horizontal groups. A basic middle situation, was considered as a cost of zero in each group and based on that, all movement costs (up, down, left or right), between every two neighbour characters within/outside of a group, are measured by sum of a set of experimental multiplying factors to the  vector difference of each those two neighbours.

With the help of python, redis and numpy, I've written a piece of code, measuring total cost of a distinct data-set of English words for 5 separated keyboard layouts: US:QWERTY, US:Dvorak, US:Colemak, US:Workman and finally my introduced US layout: Oatpie.

I made my code more clean and revised, then after a new run, the result has mentioned bellow. I hope it would be useful.

**Separate Information:**
![Stats](https://user-images.githubusercontent.com/41372159/127758373-f635740d-2a24-4813-91f2-042a6302c16e.png)

**Average:**
![Avg](https://user-images.githubusercontent.com/41372159/127758382-09b57898-4f86-4f19-9703-348ce73a8c54.png)

**Efficiency Comparison:**
![efficiency](https://user-images.githubusercontent.com/41372159/127758464-a7992080-d224-49fc-9453-f42f64806b2c.png)

**Comment by iandoug** [comment]
Are you familiar with the Keyboard Layout Analyzer?

Original is here:
http://patorjk.com/keyboard-layout-analyzer/#/main

My fork, has different scoring model:
https://klanext.keyboard-design.com/

You can use attached json, go to Configure, Import, paste json into the text block.

Have fun :-)
[oatpie.en.ansi.json.txt](https://github.com/eamouee/oatpie/files/6912272/oatpie.en.ansi.json.txt)

**Comment by eamouee** [comment]
Thank a lot, Ian

I saw your work, and your contribution. Enjoyed. It might be some other scoring factor in addition to my distancing weight system obviously. Your scores in the case of multiple entered texts, for QWERTY, Dvorak, Colemak and Workman is approximately in the same ratio than mine (at least i realized so) and For the Oatpie, they don't match at all. You measure changing left and write hands as a factor of badness, as i think, but for me, when i did design the Oatpie, was the good factor. I don't know the truth. My scoring system is totally experimental as other existing scoring systems do. I think these efforts must be continued...

Another good point for you: my running time of benchmark is too long; about 5h for 7.4 MiB of raw text. Yours is very fast...

Have fun and health

**Comment by iandoug** [comment]
You need to look at more than just distance ... for example, what happens if T, H and E are all on the same finger.

**Comment by eamouee** [comment]
Hi again,
Particularly  T,H & E doesn't happen here on an individual finger. You are right, if all alongside characters as possible, set to be on  different fingers, it achieved a better layout. However if it occurs, the weight of distance increases. In the next version of scoring system i consider it as a new multiplying factor in addition to machine learning.

Thanks to your time & ideas
